# Generated by Django 5.1.4 on 2024-12-24 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Genres',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Languages',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='MpaaRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('label', models.CharField(blank=True, default='', max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Mpaa Ratings',
                'ordering': ('type',),
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('img_path', models.CharField(max_length=255)),
                ('duration', models.IntegerField()),
                ('user_rating', models.CharField(max_length=1)),
                ('genre', models.ManyToManyField(to='web.genre')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.language')),
                ('mpaa_rating', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.mpaarating')),
            ],
            options={
                'verbose_name_plural': 'Movies',
                'ordering': ('id',),
            },
        ),
    ]
